name: Smart Contracts CI

on:
  push:
    branches: [ main ]
    paths:
      - 'backend/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'backend/**'

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
      HOLESKY_RPC_URL: ${{ secrets.HOLESKY_RPC_URL }}
      ETHERSCAN_API_KEY: ${{ secrets.ETHERSCAN_API_KEY }}

    steps:
    - uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: 'backend/package-lock.json'

    - name: Install dependencies
      working-directory: ./backend
      run: npm ci

    - name: Create env file
      working-directory: ./backend
      run: |
        echo "PRIVATE_KEY=${{ secrets.PRIVATE_KEY }}" >> .env
        echo "HOLESKY_RPC_URL=${{ secrets.HOLESKY_RPC_URL }}" >> .env
        echo "ETHERSCAN_API_KEY=${{ secrets.ETHERSCAN_API_KEY }}" >> .env

    - name: Compile contracts
      working-directory: ./backend
      run: npx hardhat compile

    - name: Run tests
      working-directory: ./backend
      run: npx hardhat test

    - name: Run coverage
      working-directory: ./backend
      run: npx hardhat coverage 